import {createHash} from 'node:crypto';
import {readdir,writeFile,readFile} from 'node:fs/promises';
async function walk(dir) {
 const result=[];
 for(const e of await readdir(dir,{withFileTypes:true})) {
  const name=`${dir}/${e.name}`;
  if(e.isDirectory())result.push(...await walk(name));
  else if(!e.name.startsWith('LICENSE'))result.push(`./${name}`);
 }
 return result.sort();
}
const assets=['./','./index.html','./styles.css','./app.js','./compat.js','./pdf-worker.js','./text-blocks.js','./text-layout.js','./storage.js','./manifest.webmanifest','./icon-192.png','./icon-512.png',...await walk('vendor')];
const hash=createHash('sha256');
for(const asset of assets)if(asset!=='./')hash.update(await readFile(asset));
const version='1.5.0-'+hash.digest('hex').slice(0,12);
await writeFile('offline-assets.js','// Generated by scripts/update-offline.mjs; all runtime resources are local.\nself.OFFLINE_VERSION = '+JSON.stringify(version)+';\nself.OFFLINE_ASSETS = '+JSON.stringify(assets,null,2)+';\n');
